export { mainKeyboard } from './main'
export { secondKeyboard } from './second'
export { courseMoneyKeyboard } from './courseMoney'
export { calcKeyboard } from './calculate'
export { recalculationKeyboard } from './recalculation'
