// export { default as PriceImage } from './prices.jpg'
// export { default as SecondTabImage } from './secondTab.jpg'
// export { default as SelectSizeImage } from './selectSize.jpg'
// export { default as SelectSneakerImage } from './selectSneaker.jpg'
// export { default as ShopImage } from './shopImage.jpg'